### ISSUE TITLE
Is there a way to identify BDS code from mode-s message itself ?

### ISSUE THREAD

**Issue by agnivade** [junzis/adsb-decode-guide#11]
> When SSR interrogates aircraft, a BDS code is included in request message ( Uplink Format - UF 4, 5, 20, or 21). This BDS code are then used by the aircraft transponder to register the type of message to be sent. But when the downlink message is transmitted, its BDS code is not included in the message (because the SSR knows what kind message it requested). 

If the bds code is not included, how do I decide what is the message type ?

**Comment by junzis** [comment]
Correct, that's the biggest challenge. We have to use different heuristic methods to test the messages types. A large part of these methods are already implemented in pyModeS (https://github.com/junzis/pyModeS). 

We are constantly working to improve them. When it is stable, we will update the document here. But for now, you have to read the source code to see those methods.

**Comment by agnivade** [comment]
Got it. Thanks !
